export const precisionGraphiteTokens = {
  color: {
    bgCanvas: "#F2F4F7",
    bgSurface: "#FFFFFF",
    bgSubtle: "#EAECF0",
    textPrimary: "#101828",
    textSecondary: "#475467",
    textMuted: "#667085",
    borderDefault: "#D0D5DD",
    borderStrong: "#98A2B3",
    accentPrimary: "#155EEF",
    accentHover: "#004EEB",
    accentActive: "#0040C1",
    accentMuted: "#E9F0FF",
    statusSuccess: "#067647",
    statusWarning: "#B54708",
    statusDanger: "#B42318",
    focusRing: "#84CAFF",
  },
  typography: {
    fontFamilyBase: '"IBM Plex Sans", "Segoe UI", Tahoma, sans-serif',
    fontFamilyMono:
      '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace',
    fontSizeXs: "12px",
    fontSizeSm: "14px",
    fontSizeMd: "16px",
    fontSizeLg: "18px",
    fontSizeXl: "20px",
    lineHeightTight: "1.25",
    lineHeightNormal: "1.5",
    lineHeightRelaxed: "1.7",
    fontWeightRegular: "400",
    fontWeightMedium: "500",
    fontWeightSemibold: "600",
    fontWeightBold: "700",
  },
  spacing: {
    xxs: "2px",
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    x2l: "32px",
    x3l: "40px",
  },
  radius: {
    sm: "6px",
    md: "8px",
    lg: "10px",
    pill: "999px",
  },
  shadow: {
    sm: "0 1px 2px rgba(16, 24, 40, 0.06)",
    md: "0 8px 20px rgba(16, 24, 40, 0.08)",
    lg: "0 18px 42px rgba(16, 24, 40, 0.12)",
  },
  motion: {
    durationFast: "120ms",
    durationBase: "180ms",
    durationSlow: "240ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
  },
} as const;

export const precisionGraphiteCssVariables: Record<string, string> = {
  "--pgc-color-bg-canvas": precisionGraphiteTokens.color.bgCanvas,
  "--pgc-color-bg-surface": precisionGraphiteTokens.color.bgSurface,
  "--pgc-color-bg-subtle": precisionGraphiteTokens.color.bgSubtle,
  "--pgc-color-text-primary": precisionGraphiteTokens.color.textPrimary,
  "--pgc-color-text-secondary": precisionGraphiteTokens.color.textSecondary,
  "--pgc-color-text-muted": precisionGraphiteTokens.color.textMuted,
  "--pgc-color-border-default": precisionGraphiteTokens.color.borderDefault,
  "--pgc-color-border-strong": precisionGraphiteTokens.color.borderStrong,
  "--pgc-color-accent-primary": precisionGraphiteTokens.color.accentPrimary,
  "--pgc-color-accent-hover": precisionGraphiteTokens.color.accentHover,
  "--pgc-color-accent-active": precisionGraphiteTokens.color.accentActive,
  "--pgc-color-accent-muted": precisionGraphiteTokens.color.accentMuted,
  "--pgc-color-status-success": precisionGraphiteTokens.color.statusSuccess,
  "--pgc-color-status-warning": precisionGraphiteTokens.color.statusWarning,
  "--pgc-color-status-danger": precisionGraphiteTokens.color.statusDanger,
  "--pgc-color-focus-ring": precisionGraphiteTokens.color.focusRing,
  "--pgc-font-family-base": precisionGraphiteTokens.typography.fontFamilyBase,
  "--pgc-font-family-mono": precisionGraphiteTokens.typography.fontFamilyMono,
  "--pgc-font-size-xs": precisionGraphiteTokens.typography.fontSizeXs,
  "--pgc-font-size-sm": precisionGraphiteTokens.typography.fontSizeSm,
  "--pgc-font-size-md": precisionGraphiteTokens.typography.fontSizeMd,
  "--pgc-font-size-lg": precisionGraphiteTokens.typography.fontSizeLg,
  "--pgc-font-size-xl": precisionGraphiteTokens.typography.fontSizeXl,
  "--pgc-line-height-tight": precisionGraphiteTokens.typography.lineHeightTight,
  "--pgc-line-height-normal": precisionGraphiteTokens.typography.lineHeightNormal,
  "--pgc-line-height-relaxed": precisionGraphiteTokens.typography.lineHeightRelaxed,
  "--pgc-font-weight-regular": precisionGraphiteTokens.typography.fontWeightRegular,
  "--pgc-font-weight-medium": precisionGraphiteTokens.typography.fontWeightMedium,
  "--pgc-font-weight-semibold": precisionGraphiteTokens.typography.fontWeightSemibold,
  "--pgc-font-weight-bold": precisionGraphiteTokens.typography.fontWeightBold,
  "--pgc-space-xxs": precisionGraphiteTokens.spacing.xxs,
  "--pgc-space-xs": precisionGraphiteTokens.spacing.xs,
  "--pgc-space-sm": precisionGraphiteTokens.spacing.sm,
  "--pgc-space-md": precisionGraphiteTokens.spacing.md,
  "--pgc-space-lg": precisionGraphiteTokens.spacing.lg,
  "--pgc-space-xl": precisionGraphiteTokens.spacing.xl,
  "--pgc-space-2xl": precisionGraphiteTokens.spacing.x2l,
  "--pgc-space-3xl": precisionGraphiteTokens.spacing.x3l,
  "--pgc-radius-sm": precisionGraphiteTokens.radius.sm,
  "--pgc-radius-md": precisionGraphiteTokens.radius.md,
  "--pgc-radius-lg": precisionGraphiteTokens.radius.lg,
  "--pgc-radius-pill": precisionGraphiteTokens.radius.pill,
  "--pgc-shadow-sm": precisionGraphiteTokens.shadow.sm,
  "--pgc-shadow-md": precisionGraphiteTokens.shadow.md,
  "--pgc-shadow-lg": precisionGraphiteTokens.shadow.lg,
  "--pgc-motion-duration-fast": precisionGraphiteTokens.motion.durationFast,
  "--pgc-motion-duration-base": precisionGraphiteTokens.motion.durationBase,
  "--pgc-motion-duration-slow": precisionGraphiteTokens.motion.durationSlow,
  "--pgc-motion-easing-standard": precisionGraphiteTokens.motion.easingStandard,
};

export function applyPrecisionGraphiteTheme(
  root: HTMLElement = document.documentElement,
): void {
  for (const [name, value] of Object.entries(precisionGraphiteCssVariables)) {
    root.style.setProperty(name, value);
  }
}
